### ISSUE TITLE
Crash during EPG import

### ISSUE THREAD

**Issue by Jalle19** [kodi-pvr/pvr.hts#31]
Crash log: http://sprunge.us/dKVF
Forum thread: http://forum.kodi.tv/showthread.php?tid=226906

The interesting part:

```
Thread 1 (LWP 645):
#0  0x7587fff4 in std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(std::string const&) () from /usr/lib/libstdc++.so.6
#1  0x659689d8 in ?? () from /usr/lib/kodi/addons/pvr.hts/pvr.hts.so
#2  0x6596da48 in CTvheadend::GetEpg(ADDON_HANDLE_STRUCT*, PVR_CHANNEL const&, long, long) () from /usr/lib/kodi/addons/pvr.hts/pvr.hts.so
#3  0x659649b0 in GetEPGForChannel () from /usr/lib/kodi/addons/pvr.hts/pvr.hts.so
#4  0x0084ccf0 in PVR::CPVRClient::GetEPGForChannel(std::shared_ptr<PVR::CPVRChannel> const&, EPG::CEpg*, long, long, bool) ()
#5  0x00853d0c in PVR::CPVRClients::GetEPGForChannel(std::shared_ptr<PVR::CPVRChannel> const&, EPG::CEpg*, long, long) ()
#6  0x00508720 in EPG::CEpg::UpdateFromScraper(long, long) ()
#7  0x00509fe8 in EPG::CEpg::LoadFromClients(long, long) ()
#8  0x0050a1d4 in EPG::CEpg::Update(long, long, int, bool) ()
#9  0x0050c5a8 in EPG::CEpgContainer::UpdateEPG(bool) ()
#10 0x0050cf24 in EPG::CEpgContainer::Process() ()
#11 0x0095a674 in CThread::Action() ()
#12 0x0095aee0 in CThread::staticThread(void*) ()
#13 0x76d17d88 in ?? () from /lib/libpthread.so.0
```

**Comment by Jalle19** [comment]
I'm just gonna go ahead and close this one, there's been some changes in Kodi itself that may have fixed it and I haven't heard anything from the person who reported the bug in the first place.
